2021-10-06 14:31:45,809 INFO    MainThread:19330 [wandb_setup.py:_flush():69] setting env: {}
2021-10-06 14:31:45,809 INFO    MainThread:19330 [wandb_setup.py:_flush():69] setting login settings: {'anonymous': 'must'}
2021-10-06 14:31:45,810 INFO    MainThread:19330 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '60799ad8a719bd5da9b3c598e65939a772d15720'}
2021-10-06 14:31:45,810 INFO    MainThread:19330 [wandb_init.py:_log_setup():342] Logging user logs to /home/inge/Pytorch-UNet/wandb/run-20211006_143145-1ahezyq3/logs/debug.log
2021-10-06 14:31:45,810 INFO    MainThread:19330 [wandb_init.py:_log_setup():343] Logging internal logs to /home/inge/Pytorch-UNet/wandb/run-20211006_143145-1ahezyq3/logs/debug-internal.log
2021-10-06 14:31:45,810 INFO    MainThread:19330 [wandb_init.py:init():375] calling init triggers
2021-10-06 14:31:45,811 INFO    MainThread:19330 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-10-06 14:31:45,811 INFO    MainThread:19330 [wandb_init.py:init():424] starting backend
2021-10-06 14:31:45,811 INFO    MainThread:19330 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-06 14:31:45,824 INFO    MainThread:19330 [backend.py:ensure_launched():135] starting backend process...
2021-10-06 14:31:45,829 INFO    MainThread:19330 [backend.py:ensure_launched():139] started backend process with pid: 19338
2021-10-06 14:31:45,830 INFO    MainThread:19330 [wandb_init.py:init():429] backend started and connected
2021-10-06 14:31:45,831 INFO    MainThread:19330 [wandb_init.py:init():477] updated telemetry
2021-10-06 14:31:45,832 INFO    MainThread:19330 [wandb_init.py:init():500] communicating current version
2021-10-06 14:31:46,421 INFO    MainThread:19330 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-06 14:31:46,421 INFO    MainThread:19330 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-06 14:31:46,792 INFO    MainThread:19330 [wandb_init.py:init():540] starting run threads in backend
2021-10-06 14:31:48,930 INFO    MainThread:19330 [wandb_run.py:_console_start():1601] atexit reg
2021-10-06 14:31:48,933 INFO    MainThread:19330 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.REDIRECT
2021-10-06 14:31:48,933 INFO    MainThread:19330 [wandb_run.py:_redirect():1480] Redirecting console.
2021-10-06 14:31:48,936 INFO    MainThread:19330 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-06 14:31:48,936 INFO    MainThread:19330 [wandb_init.py:init():565] run started, returning control to user process
2021-10-06 14:31:48,937 INFO    MainThread:19330 [wandb_run.py:_config_callback():843] config_cb None None {'epochs': 5, 'batch_size': 1, 'learning_rate': 1e-05, 'val_percent': 0.1, 'save_checkpoint': True, 'img_scale': 0.5, 'amp': False}
2021-10-06 14:31:48,971 INFO    MainThread:19330 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 1
2021-10-06 14:31:48,973 INFO    MainThread:19330 [wandb_run.py:_restore():1543] restore
2021-10-06 14:31:51,461 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 756
}

2021-10-06 14:31:51,698 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 756
}

2021-10-06 14:31:51,811 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 2256
}

2021-10-06 14:31:51,914 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 7916
}

2021-10-06 14:31:52,017 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 7916
}

2021-10-06 14:31:52,120 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7916
  total_bytes: 7916
}

2021-10-06 14:31:52,222 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7916
  total_bytes: 7916
}

2021-10-06 14:31:52,325 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7916
  total_bytes: 7916
}

2021-10-06 14:31:52,427 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7916
  total_bytes: 7916
}

2021-10-06 14:31:52,529 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7916
  total_bytes: 7916
}

2021-10-06 14:31:52,877 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7916
  total_bytes: 7916
}

2021-10-06 14:31:52,979 INFO    MainThread:19330 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7916
  total_bytes: 7916
}

2021-10-06 14:31:54,076 INFO    MainThread:19330 [wandb_run.py:_show_files():1915] logging synced files
